import Head from "next/head";
import { Container } from "@mui/material";
import ResponsiveAppBar from "@/components/Layout/Navbar";
import SubscriptionList from "@/components/Subscription/SubscriptionList";

export default function SubscriptionsPage() {
  return (
    <>
      <Head>
        <title>Subscriptions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <Container>
        <h1>Subscriptions</h1>
        <SubscriptionList />
      </Container>
    </>
  );
}
