import Head from "next/head";
import { Container } from "@mui/material";
import { MagazineList } from "@/components/Magazine/MagazineList";
import ResponsiveAppBar from "@/components/Layout/Navbar";

export default function MagazinesPage() {
  return (
    <>
      <Head>
        <title>Magazines</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <Container maxWidth="md">
        <h1>Magazines</h1>
        <MagazineList />
      </Container>
    </>
  );
}
