import Head from "next/head";
import { Container } from "@mui/material";
import Login from "@/components/Login";
import ResponsiveAppBar from "@/components/Layout/Navbar";

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <Container maxWidth="md">
        <Login />
      </Container>
    </>
  );
}
