import Head from "next/head";
import { Container } from "@mui/material";
import ResponsiveAppBar from "@/components/Layout/Navbar";
import CreateUser from "@/components/CreateUser";

export default function CreateUserPage() {
  return (
    <>
      <Head>
        <title>CreateUser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <Container maxWidth="md">
        <CreateUser />
      </Container>
    </>
  );
}
